// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckMLServiceHealth() {
  return window['go']['main']['App']['CheckMLServiceHealth']();
}

export function GetAvailableSymbols() {
  return window['go']['main']['App']['GetAvailableSymbols']();
}

export function GetCryptoData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCryptoData'](arg1, arg2, arg3);
}

export function GetMLModelInfo() {
  return window['go']['main']['App']['GetMLModelInfo']();
}

export function GetMLPrediction(arg1, arg2) {
  return window['go']['main']['App']['GetMLPrediction'](arg1, arg2);
}

export function IsRealtimeActive() {
  return window['go']['main']['App']['IsRealtimeActive']();
}

export function StartRealtime(arg1, arg2) {
  return window['go']['main']['App']['StartRealtime'](arg1, arg2);
}

export function StopRealtime() {
  return window['go']['main']['App']['StopRealtime']();
}
