// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckMLServiceHealth():Promise<boolean>;

export function GetAvailableSymbols():Promise<Array<string>>;

export function GetCryptoData(arg1:string,arg2:string,arg3:number):Promise<Array<main.CandleData>>;

export function GetMLModelInfo():Promise<main.MLModelInfo>;

export function GetMLPrediction(arg1:string,arg2:string):Promise<main.MLPrediction>;

export function IsRealtimeActive():Promise<boolean>;

export function StartRealtime(arg1:string,arg2:string):Promise<void>;

export function StopRealtime():Promise<void>;
