// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateIndicators(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CalculateIndicators'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetAllTickers() {
  return window['go']['main']['App']['GetAllTickers']();
}

export function GetKlines(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetKlines'](arg1, arg2, arg3);
}

export function GetSignals(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSignals'](arg1, arg2, arg3);
}

export function GetTicker24h(arg1) {
  return window['go']['main']['App']['GetTicker24h'](arg1);
}

export function SubscribeKline(arg1, arg2) {
  return window['go']['main']['App']['SubscribeKline'](arg1, arg2);
}
