// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateIndicators(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CalculateIndicators'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CancelOrder(arg1) {
  return window['go']['main']['App']['CancelOrder'](arg1);
}

export function GetActiveIntervals() {
  return window['go']['main']['App']['GetActiveIntervals']();
}

export function GetAllOrders() {
  return window['go']['main']['App']['GetAllOrders']();
}

export function GetAllTickers() {
  return window['go']['main']['App']['GetAllTickers']();
}

export function GetBalance() {
  return window['go']['main']['App']['GetBalance']();
}

export function GetBotStats() {
  return window['go']['main']['App']['GetBotStats']();
}

export function GetFearGreedIndex() {
  return window['go']['main']['App']['GetFearGreedIndex']();
}

export function GetIntervalStats() {
  return window['go']['main']['App']['GetIntervalStats']();
}

export function GetKlines(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetKlines'](arg1, arg2, arg3);
}

export function GetModelMetadata(arg1, arg2) {
  return window['go']['main']['App']['GetModelMetadata'](arg1, arg2);
}

export function GetOrders(arg1) {
  return window['go']['main']['App']['GetOrders'](arg1);
}

export function GetPortfolio() {
  return window['go']['main']['App']['GetPortfolio']();
}

export function GetPositions() {
  return window['go']['main']['App']['GetPositions']();
}

export function GetSentimentScore() {
  return window['go']['main']['App']['GetSentimentScore']();
}

export function GetSignals(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSignals'](arg1, arg2, arg3);
}

export function GetSignalsList() {
  return window['go']['main']['App']['GetSignalsList']();
}

export function GetTicker24h(arg1) {
  return window['go']['main']['App']['GetTicker24h'](arg1);
}

export function GetTradeHistory() {
  return window['go']['main']['App']['GetTradeHistory']();
}

export function GetTrainingStatus(arg1, arg2) {
  return window['go']['main']['App']['GetTrainingStatus'](arg1, arg2);
}

export function PlaceOrder(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['PlaceOrder'](arg1, arg2, arg3, arg4, arg5);
}

export function PredictPrice(arg1, arg2) {
  return window['go']['main']['App']['PredictPrice'](arg1, arg2);
}

export function ProcessOrdersForSymbol(arg1, arg2) {
  return window['go']['main']['App']['ProcessOrdersForSymbol'](arg1, arg2);
}

export function RunIntervalBacktest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunIntervalBacktest'](arg1, arg2, arg3, arg4);
}

export function StartBot(arg1, arg2) {
  return window['go']['main']['App']['StartBot'](arg1, arg2);
}

export function StartIntervalStrategy(arg1) {
  return window['go']['main']['App']['StartIntervalStrategy'](arg1);
}

export function StopBot() {
  return window['go']['main']['App']['StopBot']();
}

export function StopIntervalStrategy() {
  return window['go']['main']['App']['StopIntervalStrategy']();
}

export function SubscribeKline(arg1, arg2) {
  return window['go']['main']['App']['SubscribeKline'](arg1, arg2);
}

export function TrainModel(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['TrainModel'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function UpdateBotConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateBotConfig'](arg1, arg2, arg3, arg4, arg5);
}
