// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {indicators} from '../models';
import {binance} from '../models';
import {trading} from '../models';
import {sentiment} from '../models';
import {signals} from '../models';

export function CalculateIndicators(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:number):Promise<indicators.IndicatorValues>;

export function GetAllTickers():Promise<Array<binance.Ticker>>;

export function GetBalance():Promise<number>;

export function GetBotStats():Promise<trading.TradingStats>;

export function GetKlines(arg1:string,arg2:string,arg3:number):Promise<Array<binance.Kline>>;

export function GetPositions():Promise<Array<trading.Position>>;

export function GetSentimentScore():Promise<sentiment.SentimentScore>;

export function GetSignals(arg1:string,arg2:string,arg3:number):Promise<Array<indicators.Signal>>;

export function GetSignalsList():Promise<Array<signals.Signal>>;

export function GetTicker24h(arg1:string):Promise<binance.Ticker>;

export function GetTradeHistory():Promise<Array<trading.Trade>>;

export function StartBot(arg1:Array<string>,arg2:Array<string>):Promise<void>;

export function StopBot():Promise<void>;

export function SubscribeKline(arg1:string,arg2:string):Promise<void>;
